version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  sdkman: joshdholtz/sdkman@0.2.0

jobs:
  arm64-native:
    machine:
      image: ubuntu-2004:current
      resource_class: arm.medium
    steps:
      - checkout
      - docker/check:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKERHUB_PASSWORD
      - sdkman/setup-sdkman
      - sdkman/sdkman-install:
          candidate: java
          version: 17.0.7-graalce
      - run:
          name: "mvnw spring-boot:build-image"
          command: "./mvnw spring-boot:build-image"
      - docker/push:
          image: dashaun/$CIRCLE_PROJECT_REPONAME
          tag: $CIRCLE_TAG-aarch_64

workflows:
  arm64-native-workflow:
    jobs:
      - arm64-native:
          context:
            - dashaun-dockerhub
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
